import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';

test('PostgreSQL migration and trade permissions with two test identities',async()=>{
 const db=new PGlite();
 await db.exec(`
 create role anon; create role authenticated;
 create schema auth; create schema storage;
 create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
 create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 grant usage on schema auth,storage,public to anon,authenticated;
 grant execute on function auth.uid() to anon,authenticated;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);
 alter table storage.objects enable row level security;
 grant select,insert on storage.objects to anon,authenticated;
 create function storage.foldername(name text) returns text[] language sql as $$ select string_to_array(name,'/') $$;
 `);
 await db.exec(await readFile(new URL('../supabase/migrations/20261001000100_market.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../supabase/migrations/20261001000200_function_storage.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../supabase/migrations/20261002000100_manage_listings.sql',import.meta.url),'utf8'));
 const seller='11111111-1111-4111-8111-111111111111',buyer='22222222-2222-4222-8222-222222222222',image='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
 await db.query('insert into auth.users values ($1,$2,now()),($3,$4,now())',[seller,'seller@example.test',buyer,'buyer@example.test']);
 const identity=async(id)=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec(`set role ${id?'authenticated':'anon'}`);};
 const action=async(body)=>(await db.query('select public.market_action($1::jsonb) result',[JSON.stringify(body)])).rows[0].result;
 const feed=async(age,mine=false)=>(await db.query('select public.market_feed($1,$2) result',[age,mine])).rows[0].result;
 const listing={action:'create',title:'Regenjacke Grösse 104',description:'Gut erhaltene Regenjacke ohne Löcher, frisch gewaschen.',age:1,category:'Kleidung',condition:'Gut',size:'104 / 4 Jahre',location:'8000 Zürich',delivery:'Abholung nach Absprache',shipping:0,start:1000,buy:3000,days:1,image,childrenOnly:true};
 await identity(seller);
 await assert.rejects(db.query('insert into public.uploads(id,owner,path) values($1,$2,$3)',[image,seller,seller+'/'+image]),/permission denied/);
 assert.equal((await db.query('select public.register_upload($1) result',[image])).rows[0].result.path,seller+'/'+image);
 await db.query("insert into storage.objects(bucket_id,name) values('product-images',$1)",[seller+'/'+image]);
 await assert.rejects(action({...listing,age:5}));
 await assert.rejects(action({...listing,childrenOnly:false}));
 await assert.rejects(action({...listing,childrenOnly:'true'}));
 await assert.rejects(action({...listing,start:-1}));
 const {id}=await action(listing);
 await action({...listing,action:'edit',id,revision:0,title:'Regenjacke neu beschrieben'});
 assert.equal((await feed(null,true)).items.find(x=>x.id===id).title,'Regenjacke neu beschrieben');
 await assert.rejects(action({...listing,action:'edit',id,revision:0}),/inzwischen geändert/);
 await assert.rejects(action({...listing,action:'edit',id,revision:1,age:5}));
 const withdrawn=await action(listing);
 await assert.rejects(action({action:'withdraw',id:withdrawn.id,revision:0,confirm:false}),/bestätigen/);
 await action({action:'withdraw',id:withdrawn.id,revision:0,confirm:true});
 assert.equal((await feed(null,true)).items.find(x=>x.id===withdrawn.id).status,'withdrawn');
 await assert.rejects(action({...listing,action:'edit',id:withdrawn.id,revision:1}),/nicht mehr aktiv/);

 await assert.rejects(action({action:'bid',id,amount:1000,confirm:true}),/eigenes Angebot/);
 await assert.rejects(db.query("update public.listings set price=0 where id=$1",[id]),/permission denied/);
 await identity('');
 assert.equal((await feed(1)).items.length,1);
 assert.equal((await feed(1)).contacts.length,0);
 assert.equal('bidder' in (await feed(1)).items[0],false);
 await assert.rejects(feed(null,true),/anmelden/);
 await assert.rejects(action({action:'buy',id,confirm:true}),/permission denied/);
 await identity(buyer);
 await assert.rejects(action({...listing,action:'edit',id,revision:1}),/Nur eigene/);
 await assert.rejects(action({action:'withdraw',id,revision:1,confirm:true}),/Nur eigene/);
 await assert.rejects(db.query('select public.market_trade_action($1::jsonb)',[JSON.stringify(listing)]),/permission denied/);
 await assert.rejects(db.query('select * from public.uploads'),/permission denied/);
 assert.equal((await db.query('select public.can_read_image($1) ok',[seller+'/'+image])).rows[0].ok,true);
 await assert.rejects(db.query("insert into storage.objects(bucket_id,name) values('product-images',$1)",[buyer+'/unreserved']),/row-level security/);
 await assert.rejects(action({...listing}),/eigenes Produktfoto/);
 await assert.rejects(action({action:'bid',id,amount:1000,confirm:false}),/bestätigen/);
 await assert.rejects(action({action:'bid',id,amount:1000,confirm:'true'}),/bestätigen/);
 await assert.rejects(action({action:'bid',id,amount:999,confirm:true}),/niedrig/);
 await action({action:'bid',id,amount:1000,confirm:true});
 await identity(seller);
 await assert.rejects(action({...listing,action:'edit',id,revision:2}),/ersten Gebot/);
 await assert.rejects(action({action:'withdraw',id,revision:2,confirm:true}),/ersten Gebot/);
 await identity(buyer);
 await assert.rejects(action({action:'bid',id,amount:1099,confirm:true}),/niedrig/);
 await assert.rejects(action({action:'bid',id,amount:3000,confirm:true}),/Sofortkaufpreis/);
 assert.equal((await feed(null,true)).contacts.length,0);
 await action({action:'buy',id,confirm:true});
 await assert.rejects(action({action:'buy',id,confirm:true}),/nicht mehr verfügbar/);
 assert.equal((await feed(null,true)).contacts[0].email,'seller@example.test');
 await identity(seller);
 assert.equal((await feed(null,true)).contacts[0].email,'buyer@example.test');
 const second=await action({...listing,buy:null});
 const third=await action({...listing,buy:null});
 await identity(buyer);await action({action:'bid',id:second.id,amount:1000,confirm:true});
 await db.exec('reset role');await db.query('update public.listings set "end"=0 where id in ($1,$2)',[second.id,third.id]);
 await identity(buyer);
 await assert.rejects(action({action:'bid',id:second.id,amount:1100,confirm:true}),/nicht mehr verfügbar/);
 assert.equal((await feed(null,true)).items.find(x=>x.id===second.id).status,'sold');
 await identity(seller);
 assert.equal((await feed(null,true)).items.find(x=>x.id===third.id).status,'expired');
 await identity('');assert.equal((await feed(1)).items.length,0);
 await db.close();
});
