'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Order,Issue,steps,chf,date} from '@/lib/orders';
const reasons=['Zahlung','Versand oder Übergabe','Artikel entspricht nicht dem Angebot','Sonstiges'];
const eventLabels:Record<string,string>={paid:'Zahlung veranlasst',payment_received:'Zahlung erhalten',sent:'Versandt / übergeben',received:'Artikel erhalten',issue:'Problem gemeldet',resolve_issue:'Problem als gelöst bestätigt',issue_closed:'Support-Prüfung abgeschlossen'};
export default function Orders({focusedOffer='',support=false}:{focusedOffer?:string;support?:boolean}){
 const [orders,setOrders]=useState<Order[]>([]),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('open');
 const [decision,setDecision]=useState<{order:Order;action:string;issue?:Issue}|null>(null),[reason,setReason]=useState(reasons[0]),[details,setDetails]=useState(''),[confirm,setConfirm]=useState(false),[formError,setFormError]=useState('');
 const sequence=useRef(0),endpoint=support?'/api/order-support':'/api/orders';
 const load=useCallback(async()=>{const s=++sequence.current;try{const r=await fetch(endpoint,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);if(s===sequence.current){setOrders(d.orders);setError('');setLoaded(true)}}catch(e){if(s===sequence.current)setError(e instanceof Error?e.message:'Laden fehlgeschlagen.')}},[endpoint]);
 useEffect(()=>{void load();return()=>{++sequence.current}},[load]);
 useEffect(()=>{if(focusedOffer&&loaded){document.getElementById('order-'+focusedOffer)?.scrollIntoView({block:'nearest'})}},[focusedOffer,loaded]);
 function open(order:Order,action:string,issue?:Issue){setDecision({order,action,issue});setDetails('');setReason(reasons[0]);setConfirm(false);setFormError('')}
 async function save(e:React.FormEvent){e.preventDefault();if(!decision)return;setBusy(true);setFormError('');try{
  const body=support?{id:decision.issue?.id,revision:decision.order.revision,note:details,confirm}:{id:decision.order.listing,revision:decision.order.revision,action:decision.action,reason,details,note:details,issue_id:decision.issue?.id,confirm};
  const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw Error(d.error);setDecision(null);setNotice(d.message);window.dispatchEvent(new Event('market-updated'));await load();
 }catch(e){setFormError(e instanceof Error?e.message:'Nicht gespeichert.')}finally{setBusy(false)}}
 const visible=support?orders.filter(o=>filter==='open'?o.issues.some(i=>i.status==='open'):o.issues.every(i=>i.status!=='open')):orders;
 const needsText=decision&&(support||decision.action==='issue'||decision.action==='resolve_issue');
 return <section className="orders"><div className="actions"><button className="plain" onClick={()=>void load()} disabled={busy}>Abwicklung aktualisieren</button>{support&&<><button className={filter==='open'?'primary':'secondary'} onClick={()=>setFilter('open')}>Offene Verkaufsprobleme</button><button className={filter==='closed'?'primary':'secondary'} onClick={()=>setFilter('closed')}>Abgeschlossene Verkaufsprobleme</button></>}</div>
 <p className="hint">Bestätigungen der Beteiligten, kein Zahlungsnachweis. Zahlung und Übergabe vereinbart ihr direkt.{support?' Maximal 200 Verkäufe mit Problemmeldung.':' Die jüngsten 250 Verkäufe werden angezeigt.'}</p>
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}{!loaded&&!error&&<p role="status">Abwicklung wird geladen …</p>}
 <div className="order-list">{visible.map(o=>{const problem=o.issues.some(i=>i.status==='open');return <article key={o.listing} id={'order-'+o.listing} className={'order-card'+(focusedOffer===o.listing?' account-focused':'')}><h3>{o.title}</h3><p className="order-status">{problem?'Problem offen':o.completed_at?'Abgeschlossen':'In Abwicklung'}</p><p>Artikel {chf(o.price)} + Versand {chf(o.shipping)} = <b>{chf(o.price+o.shipping)}</b></p><p className="description">{o.delivery}</p><p>Käufer: {o.buyer_name} · Verkäufer: {o.seller_name}</p>{o.contact&&<a className="contact" href={'mailto:'+o.contact}>Kontakt: {o.contact}</a>}
 <ol className="order-steps">{steps.map(s=><li key={s.action}><span><b>{s.label}</b><small>{o[s.field]?date(o[s.field]!):'Noch nicht bestätigt'}</small></span>{!support&&o.role===s.role&&!o[s.field]&&<button className="secondary" disabled={busy} onClick={()=>open(o,s.action)}>Bestätigen: {s.label}</button>}</li>)}</ol>
 {o.completed_at&&<p className="hint">Alle Schritte bestätigt am {date(o.completed_at)}.{problem?' Eine spätere Problemmeldung ist noch offen.':''}</p>}
 {o.issues.map(i=><section className="order-issue" key={i.id}><h4>{i.status==='open'?'Offenes Problem':'Abgeschlossenes Problem'} · {i.role==='buyer'?'Käufer':'Verkäufer'}</h4><p><b>{i.reason}</b> · {date(i.created)}</p><p className="description">{i.details}</p>{i.review_note&&<p className="notice">{i.review_role==='support'?'Support-Begründung':'Lösung der meldenden Person'}: {i.review_note}</p>}{i.status==='open'&&(support?<button className="secondary" disabled={busy||o.role!=='support'} onClick={()=>open(o,'review',i)}>Prüfung abschliessen</button>:i.role===o.role&&<button className="secondary" disabled={busy} onClick={()=>open(o,'resolve_issue',i)}>Mein Problem ist gelöst</button>)}</section>)}
 {!support&&!o.issues.some(i=>i.role===o.role)&&<button className="plain" disabled={busy} onClick={()=>open(o,'issue')}>Problem melden</button>}
 <details><summary>Verlauf der Bestätigungen</summary>{o.events.length?<ul>{o.events.map((e,i)=><li key={i}>{date(e.created)} · {e.role==='buyer'?'Käufer':e.role==='seller'?'Verkäufer':'Support'}: {eventLabels[e.action]||e.action}</li>)}</ul>:<p>Noch keine Bestätigungen.</p>}</details></article>})}</div>
 {loaded&&!visible.length&&!error&&<p className="empty">{support?'Keine passenden Verkaufsprobleme.':'Noch keine Käufe oder Verkäufe zum Abwickeln.'}</p>}{focusedOffer&&loaded&&!orders.some(o=>o.listing===focusedOffer)&&!error&&<p className="error">Dieser Verkauf ist in dieser Übersicht nicht verfügbar.</p>}
 <Dialog open={decision!==null} onOpenChange={v=>{if(!v&&!busy)setDecision(null)}}><DialogContent className="market-dialog"><DialogTitle>{support?'Problemmeldung abschliessen':decision?.action==='issue'?'Problem melden':decision?.action==='resolve_issue'?'Problem als gelöst bestätigen':steps.find(s=>s.action===decision?.action)?.label||'Bestätigung'}</DialogTitle><DialogDescription>{decision?.order.title}. {support?'Begründung dokumentieren. Dies storniert den Kauf nicht und führt keine Rückzahlung aus. Probleme zu eigenen Verkäufen können nur von einem anderen Support-Betreiber geprüft werden.':decision?.action==='issue'?'Deine Beschreibung sehen beide Beteiligte und ausdrücklich freigeschalteter Support. Bitte keine Bankdaten, Adressen oder andere sensible Angaben eingeben.':decision?.action==='resolve_issue'?'Deine Lösung wird für die andere Person und den Support sichtbar.':'Bestätige nur, was tatsächlich erfolgt ist. Die Angabe bleibt im Verlauf gespeichert und kann hier nicht rückgängig gemacht werden.'}</DialogDescription><form className="sell-form" onSubmit={save}>
 {decision?.action==='issue'&&!support&&<label>Grund<select value={reason} onChange={e=>setReason(e.target.value)}>{reasons.map(r=><option key={r}>{r}</option>)}</select></label>}
 {needsText&&<label>{support?'Begründung':decision?.action==='resolve_issue'?'Wie wurde das Problem gelöst?':'Beschreibung des Problems'}<textarea required minLength={10} maxLength={1000} rows={4} value={details} onChange={e=>setDetails(e.target.value)}/></label>}
 <label className="checkline"><Checkbox checked={confirm} onCheckedChange={v=>setConfirm(v===true)}/>{needsText?'Ich bestätige diese Angaben.':'Ich bestätige, dass dieser Schritt erfolgt ist.'}</label><div className="actions"><button className="primary" disabled={busy||!confirm||Boolean(needsText&&details.trim().length<10)}>{busy?'Wird gespeichert …':'Angaben speichern'}</button><button className="secondary" type="button" disabled={busy} onClick={()=>setDecision(null)}>Abbrechen</button></div>{formError&&<p className="error" role="alert">{formError}</p>}</form></DialogContent></Dialog></section>;
}
