'use client';
import {useActionState,useState,useEffect} from 'react';
import {sendCode,verifyCode,signInGoogle} from './actions';
export default function Login(){
 const googleEnabled=process.env.NEXT_PUBLIC_GOOGLE_AUTH_ENABLED==='true';
 const [google,googleAction,googlePending]=useActionState(signInGoogle,{message:''});
 const [email,setEmail]=useState(''),[showCode,setShowCode]=useState(false),[callbackError,setCallbackError]=useState(false);const [send,sendAction,sending]=useActionState(sendCode,{message:'',sent:false});const [verify,verifyAction,verifying]=useActionState(verifyCode,{message:''});
 useEffect(()=>setCallbackError(new URLSearchParams(window.location.search).get('error')==='callback'),[]);
 return <main className="login-page"><a className="brand" href="/">klein<span>weiter</span></a><div className="login-card"><span className="eyebrow">DEIN KONTO</span><h1>Willkommen in der nächsten Runde.</h1><p>{googleEnabled?'Melde dich sicher mit deinem Google-Konto an. Beim ersten Mal wird dein Konto erstellt.':'Wir senden dir einen sicheren Anmeldelink per E-Mail. Beim ersten Mal wird dein Konto erstellt.'}</p>{callbackError&&<p className="error" role="alert">Die Anmeldung konnte nicht abgeschlossen werden. Starte sie erneut in diesem Browser.</p>}<form action={googleAction} hidden={!googleEnabled}><button className="primary" disabled={googlePending}>{googlePending?'Weiter zu Google …':'Mit Google anmelden'}</button>{google.message&&<p role="alert" className="error">{google.message}</p>}</form><div hidden={googleEnabled}><form action={sendAction}><label>E-Mail-Adresse<input required type="email" name="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><button className="primary" disabled={sending}>{sending?'Wird gesendet …':send.sent?'Neuen Link senden':'Anmeldelink senden'}</button></form>{send.message&&<p role="status">{send.message}</p>}{send.sent&&<><button className="plain" onClick={()=>setShowCode(!showCode)}>Du hast einen Code erhalten?</button>{showCode&&<form action={verifyAction}><input type="hidden" name="email" value={email}/><label>Code aus deiner E-Mail<input required name="token" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6,10}" minLength={6} maxLength={10}/></label><button className="primary" disabled={verifying}>{verifying?'Wird geprüft …':'Anmelden'}</button>{verify.message&&<p role="alert" className="error">{verify.message}</p>}</form>}</>}</div><p className="hint">Konten sind für erwachsene Käufer und Verkäufer. Zahlung und Übergabe vereinbart ihr direkt.</p><a className="plain" href="/">Zurück zum Marktplatz</a></div></main>;
}
